### ISSUE TITLE
bug: saving examples "converts" them to projects

### ISSUE THREAD

**Issue by amyspark-ng** [kaplayjs/kaplayground#28]
Now they will appear here on the projects tab

Also i think they break, which doesn't even make them actual projects, when clicking to them on the dropdown it actually sends you there but clicking them in the big menu sends you to the add example

![image](https://github.com/user-attachments/assets/d1002f05-3ee0-486f-aeff-afb907afd8c3)

**Comment by lajbel** [comment]
fixed on #31
